### ISSUE TITLE
This does not seem to work with the recent Ampache

### ISSUE THREAD

**Issue by gerroon** [bahamas10/Viridian#2]
Hi

I was excited to see that there was a client however it does not seem to support Ampache 3.8.0-develop. At least that is how it looks like here.

Do you have plans to update it to the latest ver?

**Comment by marxjohnson** [comment]
I am using it successfully with the latest version of Ampache.

**Comment by gerroon** [comment]
Hi

I am using https (self signed). Could that be an issue?

**Comment by gerroon** [comment]
Maybe this is the issue?

Number of artists = 3130
Traceback (most recent call last):
  File "/usr/share/viridian/AmpacheTools/AmpacheSession.py", line 777, in __call_api
    response = urllib2.urlopen(self.xml_rpc + '?' + data)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1207, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1172, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 709, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 603, in read
    v = self._sslobj.read(len or 1024)
SSLError: ('The read operation timed out',)

**Comment by marxjohnson** [comment]
I'm also using SSL, but with a properly signed certificate, so that's a possibility.
