### ISSUE TITLE
Viridian ownCloud / list index error

### ISSUE THREAD

**Issue by ghost** [bahamas10/Viridian#3]
Hello,
try to use this wonderful software with my ownCloud Music.
But when I try I get this error

``` bash
Authentication Successful!
Authentication = e723c7ca91408ffb58fc53d5500e7934
Number of artists = 183
Traceback (most recent call last):
  File "/usr/share/viridian/AmpacheTools/AmpacheSession.py", line 258, in get_artists
    artist_name = child.getElementsByTagName('name')[0].childNodes[0].data
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/share/viridian/AmpacheTools/AmpacheSession.py", line 313, in get_albums
    artist_name    = child.getElementsByTagName('artist')[0].childNodes[0].data
IndexError: list index out of range
```

Could you help me?

**Comment by bahamas10** [comment]
Hey, thanks for the interest.  Unfortunately I haven't touched Viridian in quite some time (~5 years now... time flies).

I'll try to take a look this weekend

**Comment by ghost** [comment]
Did you find anything?
